baseURL = "https://www.nextflow.io/"
languageCode = "en-us"
title = "Nextflow"
theme = "hugo-advance"
paginate = 5

pygmentsCodeFences = true
pygmentsStyle = "vs"
pygmentsOptions = "linenos=table"

[params]
    primary_color = "#28AE61"
    secondary_color = "#28AE61"
    grey_color = "#F0F0F0"
    font_family_base = "'Quicksand', sans-serif;"
    font_family_heading = "'Quicksand', sans-serif;"
    google_analytics_id = "UA-364526-10"

    google_fonts = [
      ["Raleway", "400"],
      ["Quicksand", "300"],
      ["Slabo 27px"],
      ["DM Serif Display"],
      ["Open Sans"],
      ["Montserrat", "400, 700"],
      ["Roboto", "400, 400i, 700, 700i"]
    ]

    [params.homepage_meta_tags]
        meta_description = "Scientific workflows and HPC pipelines for genomics, bioinformatics and data science at scale across clusters and cloud."
        meta_og_title = "Nextflow"
        meta_og_type = "website"
        meta_og_url = "https://www.nextflow.io"
        meta_og_image = "https://hugo-advance-pro.netlify.com/images/tn.png"
        meta_og_description = "Scientific workflows and HPC pipelines for genomics, bioinformatics and data science at scale across clusters and cloud."
        meta_twitter_card = "Scientific workflows and HPC pipelines for genomics, bioinformatics and data science at scale across clusters and cloud."
        meta_twitter_site = "https://www.nextflow.io"
        meta_twitter_creator = "Evan Floden"

    [params.global]
        header_fixed = true

    [params.footer]
        show_menu_footer_primary = true
        show_menu_footer_secondary = true
        show_services_links = true
        show_work_links = true

    [params.homepage]
        show_services_section = false
        services_count = 6

        main_image = "images/home.png"

        install_title = "Get Started"
        install_subtitle = "Nextflow can be installed on any POSIX compatible system (Linux, OS X, etc)."
        install_subsubtitle = "Simply follow these three steps."

        install_step_one_title = "Check"
        install_step_one_description = "Java 8 or later is required"
        install_step_one_command = "java -version"
        install_step_one_subtitle = "Version numbers <code class=\"text-muted\">1.8.y_z</code> and <code class=\"text-muted\">8</code> identify the same Java release."

        install_step_two_title = "Install"
        install_step_two_description = "One line installation"
        install_step_two_command = "curl -s https://get.nextflow.io | bash"
        install_step_two_subtitle = "A file nextflow is created in the current directory."

        install_step_three_title = "Launch"
        install_step_three_description = "Try a simple demo"
        install_step_three_command = "./nextflow run hello"
        install_step_three_subtitle = "Start creating and launching workflows!"

        install_link = "/docs/latest/getstarted.html"
        install_link_text = "See installation docs"

        show_partners = true
        partners_heading = "Trusted by the world's most innovative organizations since 2014"
        partners_subheading = "Along with a community of thousands of scientists, engineers and developers."

        show_work_section = false
        work_section_heading = "Our Work"
        work_count = 2
        show_view_all_work_button = true

    [params.work]
        # Work Page
        order_work_grid = 'weight' # shuffle, lastmod, weight
        show_filters = true # show filters

    [params.repo]
        url = "https://github.com/nextflow-io/nextflow"

# Main Menu
[[menu.main]]
    name = "Learn"
    url = "/learn/"
    weight = 1

[[menu.main]]
    identifier = "Docs"
    name = "Docs"
    url = "/docs/latest/"
    weight = 2

[[menu.main]]
    parent = "Docs"
    name = "Reference"
    url = "/docs/latest/"
    weight = 1

[[menu.main]]
    parent = "Docs"
    name = "Edge"
    url = "/docs/edge/"
    weight = 2

[[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 3

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 4

[[menu.main]]
    name = "Support"
    url = "/support/"
    weight = 5

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 6


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 8

# Footer Menu Primary
[[menu.footer_primary]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer_primary]]
    name = "Learn"
    url = "/learn/"
    weight = 2

[[menu.footer_primary]]
    name = "Docs"
    url = "/docs/"
    weight = 3

[[menu.footer_primary]]
    name = "Community"
    url = "/community/"
    weight = 4

[[menu.footer_primary]]
    name = "Support"
    url = "/support/"
    weight = 5

[[menu.footer_primary]]
    name = "About"
    url = "/about/"
    weight = 6

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 1

[[menu.footer_secondary]]
    name = "404"
    url = "/404/"
    weight = 2


[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"
